# Generated by Django 3.2 on 2021-04-30 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_auto_20210418_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_post',
            field=models.ManyToManyField(blank=True, default=None, related_name='saved_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
