# Generated by Django 3.2 on 2021-04-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210430_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
