# Generated by Django 3.2 on 2021-05-04 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20210504_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoprofileview',
            name='another_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='whoprofileview',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
