# Generated by Django 3.1.5 on 2021-05-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210505_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
